# Generated by Django 2.2 on 2020-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item', models.CharField(max_length=50, verbose_name='时间')),
                ('todo_date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '简单的记事本',
                'verbose_name_plural': '简单的记事本',
            },
        ),
    ]
